apiVersion: v1
kind: ConfigMap
metadata:
  name: controller-config
  namespace: {{ include "controller_ns" . }}
data:
  TASK_NAMESPACE: {{ include "tasks_ns" . }}
  NAMESPACE: {{ include "controller_ns" . }}
  BACKEND_HOST: http://backend.{{ .Release.Namespace }}.svc.cluster.local:5000
  KC_HOST: http://keycloak.{{ include "kc_ns" . }}.svc.cluster.local
  GIT_HOME: {{ template "fn-task-controller.gitpath" . }}
  MOUNT_OPTIONS: {{ join "," .Values.storage.mountOptions | quote }}
  SKIP_USER_AUTH: {{ .Values.controller.skipUserAuth | default false | quote }}
{{- if .Values.storage.local }}
  MOUNT_PATH: {{ (.Values.storage.local).path }}
{{- end }}
  PULL-POLICY: Always
  TAG: {{ (.Values.controller).tag | default .Chart.AppVersion }}
  STORAGE_CLASS: {{ include "controllerStorageClass" . }}
  CRD_GROUP: {{ include "controllerCrdGroup" . }}
{{- if (.Values.global).taskReview }}
  TASK_REVIEW: enabled
{{- end }}
  IMAGE: {{ template "fn-task-controller.helper-image" . }}
  PUBLIC_URL: {{ (.Values.global).host | default "federated-node" }}
{{- if .Values.storage.aws }}
  AWS_STORAGE_ENABLED: "true"
  AWS_STORAGE_DRIVER: "efs.csi.aws.com"
  AWS_FILES_SYSTEM_ID: {{ include "awsStorageAccount" . }}
{{- end }}
{{- if .Values.storage.azure }}
  AZURE_STORAGE_ENABLED: "true"
  AZURE_SHARE_NAME: {{ .Values.storage.azure.shareName }}
  AZURE_SECRET_NAME: {{ .Values.storage.azure.secretName | default "azure-storage-secret" }}
{{- end }}
{{- if .Values.storage.gcp }}
  GCP_STORAGE_ENABLED: "true"
  GCP_VOLUME_HANDLE: {{ .Values.storage.gcp.volumeHandle }}
  GCP_FILESTORE_IP: {{ .Values.storage.gcp.ip }}
  GCP_SHARE_NAME: {{ .Values.storage.gcp.shareName }}
{{- end }}
