apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-operator
  namespace: {{ include "controller_ns" . }}
  labels:
    app: analytics-operator
  annotations:
    rollme: {{ template "rollMe" . }}
    helm.sh/hook-weight: "2"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analytics-operator
  template:
    metadata:
      {{- if .Values.storage.gcp }}
      annotations:
        gke-gcsfuse/volumes: "true"
      {{- end }}
      labels:
        app: analytics-operator
    spec:
      serviceAccountName: analytics-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      volumes:
        - name: git
          persistentVolumeClaim:
            claimName: {{ include "pvcControllerName" . }}
        - name: destinations
          configMap:
            name: controller-delivery-config
            items:
            - key: delivery.json
              path: delivery.json
      initContainers:
        - name: storage-init
          image: "{{ include "fn-task-controller.helper-image" . }}:{{ .Values.controller.tag | default .Chart.AppVersion }}"
          command: ["/bin/sh"]
          args:
            - -c
            - mkdir -p /mnt/storage/controller
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: git
              mountPath: /mnt/storage
        - name: controller-user-init
          image: "{{ include "fn-task-controller.helper-image" . }}:{{ .Values.controller.tag | default .Chart.AppVersion }}"
          command: ["python3", "-u", "create-controller-user.py"]
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          envFrom:
            - configMapRef:
                name: controller-config
            - secretRef:
                name: controller-user-creds
            - secretRef:
                name: kc-secrets
          env:
            - name: KEYCLOAK_NAMESPACE
              value: {{ include "kc_ns" . }}
      containers:
      - name: analytics-operator
        image: {{ template "fn-task-controller.image" . }}:{{ (.Values.controller).tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        envFrom:
          - configMapRef:
              name: controller-config
        env:
          - name: KC_USER
            valueFrom:
              secretKeyRef:
                name: controller-user-creds
                key: SYS_USER_EMAIL
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        volumeMounts:
          - name: git
            mountPath: {{ template "fn-task-controller.gitpath" . }}
            subPath: controller
          - name: destinations
            mountPath: /app/controller/delivery.json
            subPath: delivery.json
